services:
  # Backend API
  - type: web
    name: biscuitbreaker-backend
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 82103457396-ghfe9hichc8ru7k6ijmmicnrcffu5id5.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: ALLOWLIST
        value: bbreakergaming@gmail.com,vinay_rayana@srmap.edu.in,vinayrayana@gmail.com
      - key: DATABASE_URL
        fromDatabase:
          name: biscuitbreaker-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: biscuitbreaker-frontend
          property: host
      - key: GOOGLE_CALLBACK_URL
        value: https://biscuitbreaker-backend.onrender.com/api/auth/google/callback

  # Frontend React App
  - type: web
    name: biscuitbreaker-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: biscuitbreaker-backend
          property: host

# PostgreSQL Database
databases:
  - name: biscuitbreaker-db
    databaseName: biscuitblog
    user: biscuitbreaker
    region: oregon
    plan: free